---
title: Agency-level fatal police shootings over time
author: ''
date: '2023-04-09'
slug: agency-level-fatal-police-shootings-over-time
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2023-04-09T18:56:03-04:00'
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)

library(tidyverse)
library(shiny)
library(plotly)


```

<!-- ## Import -->

```{r remedy001, include=FALSE}
## Or PULL DIRECTLY FROM WAPO GITHUB

urlfile="https://raw.githubusercontent.com/jnixy/agency-level-fatal-OIS/main/agency-level-fatal-ois.csv"

df_all <-read_csv(url(urlfile))

```


<!-- ## Shiny version of the "by agency over time" above -->

```{r remedy004, echo=FALSE}


# Reshape the data to long format
df_long <- df_all %>%
  pivot_longer(-year, names_to = "agency", values_to = "shootings") %>%
  drop_na(shootings) # drop rows with missing data

# Define user interface for the app
ui <- fluidPage(
  titlePanel("Police Shootings by Agency over Time"),
  sidebarLayout(
    sidebarPanel(
      selectizeInput("selected_agency", "Select Agency:",
                     choices = unique(df_long$agency), selected = unique(df_long$agency)[1],
                     options = list(placeholder = 'Type or select an agency'))
    ),
    mainPanel(
      plotlyOutput("agency_plot")
    )
  )
)

# Define server logic for the app
server <- function(input, output) {
  output$agency_plot <- renderPlotly({
    df_filtered <- df_long[df_long$agency == input$selected_agency, ]
    p <- ggplot(df_filtered, aes(x = year, y = shootings, group = agency, text = paste("Year:", year, "Shootings:", shootings))) +
      geom_line(color="blue") +
      geom_point() +
      scale_x_continuous(limits = c(1970, NA)) +
      labs(x = "Year", y = "Shootings", title = "CourtesY: Dr. Justin Nix (original data) & Dr. Ian Adams (visualization)") +
      theme_minimal()
    
    ggplotly(p, tooltip = "text")
  })
}

# Run the app
shinyApp(ui = ui, server = server)
```



