---
# Documentation: https://wowchemy.com/docs/managing-content/

title: "Latex Equations From Model Objects the Equatiomatic Package"
subtitle: ""
summary: ""
authors: []
tags: []
categories: []
date: 2021-01-18T19:27:18-07:00
lastmod: 2021-01-18T19:27:18-07:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<p>As I was building a recent preprint, and trying to translate a long Bayesian formula (courtesy the big brain of <a href="https://smourtgos.netlify.app/">Scott Mourtgos</a>) into properly specified LaTeX, I thought there has to be a better way. As usual, my decision to <a href="https://github.com/andrewheiss">follow Andrew Heiss’ github</a> paid off, as I saw he has been authoring the <code>equatiomatic</code> package. The project is maintained by Daniel Anderson, and you can <a href="https://datalorax.github.io/equatiomatic/">check it out yourself here</a>.</p>
<p>The beauty of <code>equatiomatic</code> is clear - it takes your model object in R and translates it into beautifully rendered LaTeX equations.</p>
<p>Thought I’d quickly demo the package using some easy data I had laying around.</p>
<div id="walking-through-equatiomatic" class="section level2">
<h2>Walking Through <code>equatiomatic</code></h2>
<p>First get the package installed and loaded:</p>
<pre class="r"><code># package install
# install.packages(&quot;equatiomatic&quot;, repos = &quot;http://cran.us.r-project.org&quot;)

# load up
library(equatiomatic)</code></pre>
<p>I’m using some data from my most recent publication in <em>Public Administration Review</em>, which tests competing theories of body-worn camera (BWC) activation. We ask: Is variation in BWC activations more explained by officer attitudes towards the cameras, by officer demographics, or by job function. I won’t repeat the whole analysis here, but you can <a href="https://doi.org/10.1111/puar.13339">find out by visiting the article</a>!</p>
<pre class="r"><code>library(tidyverse)

activations &lt;- read_csv(&quot;activations.csv&quot;)

head(activations)</code></pre>
<pre><code>## # A tibble: 6 x 26
##   totalactivations Activ_Plus_One_~ years_LEO Female  rank BWC_time forcecount
##              &lt;dbl&gt;            &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
## 1               54             4.01         4      0     1        5          0
## 2               79             4.38        10      0     1        3          0
## 3              138             4.93         4      0     1        5          1
## 4               11             2.48        11      0     1        5          0
## 5              148             5.00        20      0     1        5          0
## 6              198             5.29         3      0     1        4          1
## # ... with 19 more variables: totalprimarycalls &lt;dbl&gt;, arrests &lt;dbl&gt;,
## #   Line_Officer &lt;dbl&gt;, BWCapproval_new &lt;dbl&gt;, POS_LATENT &lt;dbl&gt;,
## #   BWC_understand &lt;dbl&gt;, BWC_freedom &lt;dbl&gt;, BWC_decision &lt;dbl&gt;,
## #   BWC_manipulate &lt;dbl&gt;, BWC_modify &lt;dbl&gt;, BWC_lessforce &lt;dbl&gt;,
## #   BWC_assault &lt;dbl&gt;, BWC_complaint &lt;dbl&gt;, BWC_personal &lt;dbl&gt;,
## #   BWC_embarrass &lt;dbl&gt;, BWC_hatred &lt;dbl&gt;, BWC_fair &lt;dbl&gt;, BWC_protect &lt;dbl&gt;,
## #   BWC_wellbeing &lt;dbl&gt;</code></pre>
<p>Let’s build a quick (and misspecified here) version of one of the main models of interest in the paper:</p>
<pre class="r"><code>job_function &lt;- lm(totalactivations ~ forcecount + totalprimarycalls + arrests + Line_Officer, activations)</code></pre>
<p>Now, we give the results of that model to <code>equatiomatic</code> and let it extract and build:</p>
<pre class="r"><code>equatiomatic::extract_eq(job_function,
                         wrap = TRUE,        # Long equation needs to wrap 
                         terms_per_line = 2) # Max two equation terms per line</code></pre>
<pre><code>## $$
## \begin{aligned}
## \operatorname{totalactivations} &amp;= \alpha + \beta_{1}(\operatorname{forcecount})\ + \\
## &amp;\quad \beta_{2}(\operatorname{totalprimarycalls}) + \beta_{3}(\operatorname{arrests})\ + \\
## &amp;\quad \beta_{4}(\operatorname{Line\_Officer}) + \epsilon
## \end{aligned}
## $$</code></pre>
<p>We can take the output directly to Rmarkdown using the given LaTeX!</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{totalactivations} &amp;= \alpha + \beta_{1}(\operatorname{forcecount})\ + \\
&amp;\quad \beta_{2}(\operatorname{totalprimarycalls}) + \beta_{3}(\operatorname{arrests})\ + \\
&amp;\quad \beta_{4}(\operatorname{Line\_Officer}) + \epsilon
\end{aligned}
\]</span></p>
<p>Absolutely gorgeous! But it gets better, we can include the coefficients instead of funny Greek letters!</p>
<pre class="r"><code>equatiomatic::extract_eq(job_function,
                         use_coefs = TRUE,   # Use coefficients instead of beta
                         wrap = TRUE,        # Long equation needs to wrap 
                         terms_per_line = 2) # Max two equation terms per line</code></pre>
<pre><code>## $$
## \begin{aligned}
## \operatorname{totalactivations} &amp;= 6.19 + 10.66(\operatorname{forcecount})\ + \\
## &amp;\quad 0.65(\operatorname{totalprimarycalls}) + 3.91(\operatorname{arrests})\ + \\
## &amp;\quad 18.78(\operatorname{Line\_Officer}) + \epsilon
## \end{aligned}
## $$</code></pre>
<p>Again, copy/paste over the LaTeX given by equatiomatic, and:</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{totalactivations} &amp;= 6.19 + 10.66(\operatorname{forcecount})\ + \\
&amp;\quad 0.65(\operatorname{totalprimarycalls}) + 3.91(\operatorname{arrests})\ + \\
&amp;\quad 18.78(\operatorname{Line\_Officer}) + \epsilon
\end{aligned}
\]</span></p>
<p>By the way, the package isn’t limited to linear regressions, and already has support for logistic and probit regressions with <code>glm()</code>, and ordered logistic regressions. Hit up the package home to follow development.</p>
<p>I am completely impressed by this young package so far, and can’t wait to see what else is coming!</p>
</div>
