---
title: The Tyranny of Feeling
author: ''
date: '2016-01-13'
slug: tyranny-of-feeling
categories: []
tags:
  - police
  - trauma
subtitle: ''
summary: ''
authors: []
lastmod: '2016-06-1T09:23:12-06:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

“That’s the problem with police, you don’t show enough feeling,” she said. “You don’t feel enough.” She’s right, of course.

A drowning in a desert town with no lakes. My partner jumped into the canal and pushed the huge man to the bank. I struggled and pulled, he pushed and slipped, both of us wet and covered with mud, neither of us feeling the cold water.  Our new officer arrived and jumped into the scene, pushing on the man’s chest while I hovered over his face, trying to see inside his mouth. His wife, hands on my shoulders, screaming in my ear, screaming no. I couldn’t feel her breath on my neck, her tears on my head. Finally, my partner says to stop, just stop. I looked down and saw my pants were covered in the man’s blood, which had poured from the bullet hole in his temple. I couldn’t feel the wet blood soaking through my pants. She’s right, of course, I couldn’t feel enough.

A gunshot in the basement of a home. As I made my way down the stairs, the air was filled with a haze. A man, missing his face, and a rifle sitting in a lake of blood on the bed. Three walls covered with meat. The mewling, writhing figure unable to speak, but clearly letting me know the horror, the pain he was feeling. A few inches of jaw, glued to the carpet, the stubble of beard visible from the inside. The home now filled with explosive gas, a mother unaware. A mother begging us to just let her son die. As I grabbed the woman by the arm, I couldn’t feel her brittle, old bones under my grip. I couldn’t smell the gas, couldn’t gag as I pulled the jaw from the carpet; I couldn’t find it inside me to feel the horror. She’s right, of course, I couldn’t feel enough.

A mother, worn by the chemotherapy, held hostage. A son, a mind broken by drugs and now holding mom hostage until a girlfriend returns. I can’t feel the gun in my hands. A plan develops, a promise of a drink for a thirsty mother, worn by the long negotiation. A foot through the door, a son brings the knife towards my partner. I can’t feel my friend get cut. I can’t feel my gun, screwed into the temple of a man who’s so close to having a mind broken by a bullet. “I’ve got the knife,” the officer behind me yells. I can’t feel the relief. She’s right, of course, I couldn’t feel enough.

A breathing problem, a medical call, leave it for the medics. But I’m here, and this lady isn’t breathing, won’t breathe again. I can’t feel her granddaughter behind me, watching me place shock pads on grandma’s chest, watching me push helplessly on grandma as the machine tells me to push harder. Later now, the medics gone. As her husband pulls me into a hug, I can’t feel his heart breaking inside. Her husband has to say goodbye, and I go to her first. I never knew her, but she wouldn’t want to be seen like this, not for a goodbye. I pull a breathing tube from her throat, I can’t feel the bulb catch on her teeth, her stiffening jaw fighting this release. I pull on the bone needles screwed into her shins, I can’t feel how diabetes has scarred her lower legs. I wipe the blood from her nose and mouth, I can’t feel how cold the blood already is. She’s right, of course, I couldn’t feel enough.

A naked monster, celebrating his first day outside of prison with a cocktail of street drugs and liquor, kicking in the door. A boy, just eight, standing behind the door, holding a bat to protect his four-year-old sister from the monster outside. I can’t feel their panic, I don’t know they stand just feet from where the monster and I fight. I can’t feel his fingernails, carving deep and bloody into my arm. I can’t feel the burning as sweat, blood, and mace spray mix into the bloody cuts. He can’t feel the pain, he’s well beyond feeling. As he breaks the porch, breaks the door, breaks my skin, breaks the quiet peace of the neighborhood, I can’t feel his hair in both my hands, pulling him back from the sidewalk where he slams his head. Even today, I can’t feel those five long scars on my arm. She’s right, of course, I couldn’t feel enough.

A stolen car, a property crime. A man, too much time inside bars, reaching for the gun wrapped in a white t-shirt, cleaner than any of his other clothing. I can’t feel his hands around my waist as we fight, as we drag him from the car. I can’t feel the cars driving by us as I punch. His girlfriend screams, but I can’t feel her fear. As I continue to punch, five, six, seven hits, why won’t he stop? My wrist breaks, but I can’t feel that right now. “I’ll give you this,” he says later as we laugh together, “you boys know how to get down. I ain’t never been punched like that.” I can’t feel this admiration, can’t feel how sometimes the only one who understands is the guy you have to fight on the other side of the game. Months later, putting together another Lego set for my son. He can’t feel the bone inside my wrist give too much, the sharp pain that makes me gasp. I can’t feel the wrist, the back, the shoulder that has given too much. She’s right, of course, I couldn’t feel enough.

Another friend, another loss. Years ago now, he pulled that girl out of the cold creek, did he feel how her six-year-old body was too heavy, too water-soaked? She was the same age as his daughter, his daughter the same age as mine. His daughter’s hand-made cards alongside my daughter’s on the fridge. He’d felt enough; he must’ve had enough. 

