---
title: SPSS Cheat Sheet
author: Ian Adams
date: '2020-12-28'
slug: spss-cheat
categories:
  - SPSS
tags:
  - '6002'
linktitle: ""
summary: ~
lastmod: "`r Sys.Date()`"
toc: true
type: docs
menu:
  example:
    name: SPSS Homebrew Cheatsheet
    weight: 2
---

# SPSS Cheat Sheet

This contains some of the most common SPSS procedures for basic data analysis. 

## Data Cleaning

### Missing Data Counts

1. `Analyse` >> `Descriptive Statistics` >> `Frequencies`
2. Select the variable(s)
3. Click `Continue` and then `OK`

Missing data counts will be at the top of the resulting output.

### Edit Variable Name

1. `Transform` >> `Recode into Same Variables...`
2. Select the variable to transform and move it into the right column.
3. Click `Old and New Values...`
4. Under `Old Value`, enter either a specific value you would like to replace or a set of values you would
like to replace.
5. Under `New Value`, enter what the replacement value should be.
6. Click `Add` under `New Value`.
7. Click `Continue` and then `OK`.

### Create a Variable

1. `Transform` >> `Compute Variable...`
2. Click `Type and Label...` to set the variable type, then click `Continue`.
3. Enter the value for the variable. If it is a string, include the value in quotes.
4. Or just enter a formula for the variable based on the existing variables.
5. Click“`OK`.

### Delete a Variable

1. Right-click on the column header
2. Click `Clear`.

**NOTE:** This does not produce a syntax in the Output window. The syntax for deleting a variable is here, in case you
are saving your syntax:

-  DELETE VARIABLES [list of variables, separated by spaces].

### Drop observations based on some condition (Keep observations meeting the opposite)

1. `Data` >> `Select Cases...` >> Select `If condition is satisfied` >> `If...`
2. Enter the condition based on which observations you would like to keep, then click `Continue`.
3. Select `Delete unselected cases`.
4. Click `OK`.

You can specify multiple conditions at the same time by separating them with `AND` or `OR.`

### Merging datasets

1. `Data` >> `Merge Files` >> `Add Variables...`
2. Note that the datasets you are merging must already be saved as SPSS (.sav) format files. In addition,
the variables you are matching on must have the same name across datasets.
3. Select `An external SPSS statistics data file`, browse for your file, and select it.
4. Select `Match cases on key variables`, click on the matching variable, and add it to `Key Variables`.
5. Click `OK`.

### Appending datasets

1. `Data` >> `Merge Files` >> `Add Cases...`
2. Note that the datasets you are merging must already be saved as SPSS (.sav) format files. In addition,
the variables you are matching on must have the same name across datasets.
3. Select `An external SPSS statistics data file`, browse for your file, and select it.
4. All variables already in both datasets will appear in `Variables in New Active Dataset`, and variables
not in both datasets will be in `Unpaired Variables`. Move all unpaired variables you want into the
right column.
5. Click `OK`.

## Descriptive Statistics

### Central tendency: mean, median, and mode (for continuous variable)

1. `Analyze` >> `Descriptive Statistics` >> `Frequencies`
2. Select the continuous variable(s)
3. Uncheck `Display frequency tables`
4. Click `Statistics...` and check the desired central tendency measures
5. Click `Continue` and then `OK`

### Central tendency: mode and frequency table (for categorical variable)

1. `Analyze` >> `Descriptive Statistics` >> `Frequencies`
2. Select the categorical variable(s)
3. Check `Display frequency tables`
4. Click `Format` and select `Descending counts`
5. Click `Continue` and then `OK`

The top item in the frequency table is the mode. Note that if multiple categorical variables are selected, a
separate frequency table will be created for each variable.

### Variability: Standard deviation, variance, and range (for continuous variable)

1. `Analyze` >> `Descriptive Statistics` >> `Descriptives`
2. Select the continuous variable(s)
3. Click `Options` and select the desired measures of spread
4. Click `Continue` and then `OK`

## Common Analyses

### Correlations

#### Pearson correlation:

1. `Analyze` >> `Correlate` >> `Bivariate`
2. Select Pearson under Correlation Coefficients box, select the variables, click `OK`

#### Spearman correlation coefficient:

1. `Analyze` >> `Correlate` >> `Bivariate`
2. Select Spearman under Correlation Coefficient box, select the variables, click `OK`


### Linear Regression

#### Simple Linear Regression:

1. `Analyze` >> `Regression` >> `Linear`
2. Enter IV and DV, Click `OK`

#### Multiple Linear Regression:

1. `Analyze` >> `Regression` >> `Linear`
2. Select IVs and DV, Click `OK`

### T-Test

#### Single-Sample T-test:

1. `Analyze` >> `Compare Means` >> `One-Sample T-test`
2. Enter variables, click OK

#### Independent Samples T-test:

1. `Analyze` >> `Compare Means` >> `Independent Samples T test`
2. Enter DV (Test Variable) and IV (Grouping variable), Define Groups, and enter the values of the two levels of the IV, click `continue`, click `OK`

#### Paired Samples T-Test:

1. `Analyze` >> `Compare Means` >> `Paired Samples T Test`
2. Click on two paired variables to move to Current Selections area, then click right arrowto move to Paired Variables Section, Click `OK`

### ANOVAs

#### Oneway ANOVA:

1. `Analyze` >> `Compare Means` >> `One-Way ANOVA`
2. Enter IV in Factor box, Enter DV to Dependent List box, click `Options` >> `Descriptive` to get means in output Click continue, click OK

#### Factorial Anova (2x2, 2x2x3, etc.):

1. `Analyze` >> `General Linear Model` >> `Univariate`
2. Select DV for Dependent Variable blank and IVs for the Fixed Factors box, click `OK`

#### Repeated Measures ANOVA:

1. `Analyze` >> `General Linear Model` >> `Repeated Measures`
2. Enter factors and number of levels >> click `Add` >> once all factors are entered click `define`
3. Define variables using the arrows, click `OK`

#### Mixed-Design ANOVA:

1. Follow same steps as repeated measures
2. Add between-subjects factor to “Between-Subjects Factor” box, click `OK`
