import { useState, useEffect, useMemo } from 'react';
import type { PlotParams } from 'react-plotly.js';
import { DARK_LAYOUT, LIGHT_LAYOUT } from './types';

// Client-side only Plot component wrapper
function PlotWrapper(props: PlotParams) {
  const [Plot, setPlot] = useState<React.ComponentType<PlotParams> | null>(null);

  useEffect(() => {
    import('react-plotly.js').then((mod) => {
      setPlot(() => mod.default);
    });
  }, []);

  if (!Plot) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-700 dark:border-primary-400"></div>
      </div>
    );
  }

  return <Plot {...props} />;
}

// Data from Tregle, Nix & Alpert (2018) Table 1
interface BenchmarkData {
  id: string;
  name: string;
  shortName: string;
  category: 'population' | 'interaction' | 'arrest';
  description: string;
  limitation: string;
  years: {
    2015: { black: number; white: number; blackShot: number; whiteShot: number };
    2016: { black: number; white: number; blackShot: number; whiteShot: number };
    2017: { black: number; white: number; blackShot: number; whiteShot: number };
  };
}

const benchmarkData: BenchmarkData[] = [
  {
    id: 'population',
    name: 'Total Population',
    shortName: 'Population',
    category: 'population',
    description: 'US Census population figures. Assumes everyone has equal likelihood of police contact.',
    limitation: 'Fundamentally flawed: not everyone encounters police equally. Most people never interact with officers in situations that could become lethal.',
    years: {
      2015: { black: 39908095, white: 232943055, blackShot: 259, whiteShot: 497 },
      2016: { black: 40241818, white: 233657078, blackShot: 234, whiteShot: 466 },
      2017: { black: 41366336, white: 235494966, blackShot: 223, whiteShot: 458 },
    },
  },
  {
    id: 'police_contacts',
    name: 'Police-Initiated Contacts',
    shortName: 'Police Contacts',
    category: 'interaction',
    description: 'Estimated involuntary interactions with police from the Police-Public Contact Survey (PPCS).',
    limitation: 'Data from 2011 PPCS (most recent available). Most contacts are minor and unlikely to escalate to lethal force.',
    years: {
      2015: { black: 2542400, white: 16642200, blackShot: 259, whiteShot: 497 },
      2016: { black: 2542400, white: 16642200, blackShot: 234, whiteShot: 466 },
      2017: { black: 2542400, white: 16642200, blackShot: 223, whiteShot: 458 },
    },
  },
  {
    id: 'traffic_stops',
    name: 'Traffic Stops',
    shortName: 'Traffic Stops',
    category: 'interaction',
    description: 'Estimated traffic stops (driver or passenger) from PPCS.',
    limitation: 'Traffic stops rarely escalate to lethal force. Does not account for differences in driving behavior or vehicle conditions.',
    years: {
      2015: { black: 2001000, white: 13997700, blackShot: 259, whiteShot: 497 },
      2016: { black: 2001000, white: 13997700, blackShot: 234, whiteShot: 466 },
      2017: { black: 2001000, white: 13997700, blackShot: 223, whiteShot: 458 },
    },
  },
  {
    id: 'street_stops',
    name: 'Street Stops',
    shortName: 'Street Stops',
    category: 'interaction',
    description: 'Estimated investigative street stops from PPCS where police suspected wrongdoing.',
    limitation: 'Street stops may themselves reflect biased policing practices.',
    years: {
      2015: { black: 541400, white: 2644500, blackShot: 259, whiteShot: 497 },
      2016: { black: 541400, white: 2644500, blackShot: 234, whiteShot: 466 },
      2017: { black: 541400, white: 2644500, blackShot: 223, whiteShot: 458 },
    },
  },
  {
    id: 'total_arrests',
    name: 'Total Arrests',
    shortName: 'All Arrests',
    category: 'arrest',
    description: 'All arrests reported to the FBI Uniform Crime Report.',
    limitation: 'Most arrests are for minor offenses where lethal force is rarely needed. Arrest data may reflect enforcement patterns.',
    years: {
      2015: { black: 2197140, white: 5753212, blackShot: 259, whiteShot: 497 },
      2016: { black: 2263112, white: 5858330, blackShot: 234, whiteShot: 466 },
      2017: { black: 2221697, white: 5626140, blackShot: 223, whiteShot: 458 },
    },
  },
  {
    id: 'violent_arrests',
    name: 'Violent Crime Arrests',
    shortName: 'Violent Crime',
    category: 'arrest',
    description: 'Arrests for murder, rape, robbery, or aggravated assault—situations with higher potential for lethal force.',
    limitation: 'Not all fatal OIS stem from violent crime situations. Arrest data generated by police may reflect bias.',
    years: {
      2015: { black: 140543, white: 232180, blackShot: 259, whiteShot: 497 },
      2016: { black: 153341, white: 241063, blackShot: 234, whiteShot: 466 },
      2017: { black: 151744, white: 236590, blackShot: 223, whiteShot: 458 },
    },
  },
  {
    id: 'weapons_arrests',
    name: 'Weapons Offense Arrests',
    shortName: 'Weapons Offenses',
    category: 'arrest',
    description: 'Arrests for carrying or possessing weapons—situations most likely to require lethal response.',
    limitation: '80%+ of fatal OIS involve armed suspects. But not all OIS stem from weapons situations.',
    years: {
      2015: { black: 44284, white: 63967, blackShot: 259, whiteShot: 497 },
      2016: { black: 51898, white: 69414, blackShot: 234, whiteShot: 466 },
      2017: { black: 56143, white: 68787, blackShot: 223, whiteShot: 458 },
    },
  },
];

function calculateOddsRatio(
  blackShot: number,
  whiteShot: number,
  blackBenchmark: number,
  whiteBenchmark: number
): number {
  const blackRate = blackShot / blackBenchmark;
  const whiteRate = whiteShot / whiteBenchmark;
  return blackRate / whiteRate;
}

export default function DisparityBenchmarkSimulator() {
  const [activeTab, setActiveTab] = useState('problem');
  const [selectedYear, setSelectedYear] = useState<2015 | 2016 | 2017>(2015);
  const [selectedBenchmark, setSelectedBenchmark] = useState('population');
  const [isDark, setIsDark] = useState(false);

  // Custom scenario inputs
  const [customBlackShot, setCustomBlackShot] = useState(259);
  const [customWhiteShot, setCustomWhiteShot] = useState(497);
  const [customBlackBenchmark, setCustomBlackBenchmark] = useState(39908095);
  const [customWhiteBenchmark, setCustomWhiteBenchmark] = useState(232943055);

  // Check dark mode
  useEffect(() => {
    const checkDark = () => {
      setIsDark(document.documentElement.classList.contains('dark'));
    };
    checkDark();
    const observer = new MutationObserver(checkDark);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => observer.disconnect();
  }, []);

  // Calculate all odds ratios for comparison chart
  const allOddsRatios = useMemo(() => {
    return benchmarkData.map((b) => {
      const yearData = b.years[selectedYear];
      const or = calculateOddsRatio(
        yearData.blackShot,
        yearData.whiteShot,
        yearData.black,
        yearData.white
      );
      return {
        id: b.id,
        name: b.shortName,
        category: b.category,
        oddsRatio: or,
        interpretation: or > 1
          ? `Black ${or.toFixed(2)}x more likely`
          : `Black ${(1/or).toFixed(2)}x less likely`,
      };
    });
  }, [selectedYear]);

  // Get current benchmark data
  const currentBenchmark = benchmarkData.find((b) => b.id === selectedBenchmark)!;
  const currentYearData = currentBenchmark.years[selectedYear];
  const currentOddsRatio = calculateOddsRatio(
    currentYearData.blackShot,
    currentYearData.whiteShot,
    currentYearData.black,
    currentYearData.white
  );

  // Custom odds ratio
  const customOddsRatio = calculateOddsRatio(
    customBlackShot,
    customWhiteShot,
    customBlackBenchmark,
    customWhiteBenchmark
  );

  const tabs = [
    { id: 'problem', label: 'The Denominator Problem' },
    { id: 'compare', label: 'Benchmark Comparison' },
    { id: 'explore', label: 'Interactive Explorer' },
    { id: 'custom', label: 'Build Your Own' },
  ];

  const baseLayout = isDark ? DARK_LAYOUT : LIGHT_LAYOUT;

  return (
    <div>
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-4xl md:text-5xl font-serif font-bold text-primary-900 dark:text-gray-100 mb-4">
          Disparity Benchmark Simulator
        </h1>
        <p className="text-xl text-gray-600 dark:text-gray-400 max-w-3xl">
          Explore how your choice of denominator can completely change—even reverse—conclusions
          about racial disparities in police use of force. Based on{' '}
          <a
            href="https://doi.org/10.1080/0735648X.2018.1547269"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent-burgundy dark:text-accent-gold hover:underline"
          >
            Tregle, Nix & Alpert (2018)
          </a>.
        </p>
      </div>

      {/* Year Selector */}
      <div className="mb-6">
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
          Select Year
        </label>
        <div className="flex gap-2">
          {([2015, 2016, 2017] as const).map((year) => (
            <button
              key={year}
              onClick={() => setSelectedYear(year)}
              className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                selectedYear === year
                  ? 'bg-primary-700 text-white'
                  : 'bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700'
              }`}
            >
              {year}
            </button>
          ))}
        </div>
      </div>

      {/* Tab Navigation */}
      <div className="border-b border-gray-200 dark:border-gray-700 mb-6">
        <nav className="flex space-x-4 overflow-x-auto">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-2 text-sm font-medium whitespace-nowrap border-b-2 transition-colors ${
                activeTab === tab.id
                  ? 'border-primary-700 text-primary-700 dark:border-primary-400 dark:text-primary-400'
                  : 'border-transparent text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </nav>
      </div>

      {/* Tab Content */}
      <div style={{ display: activeTab === 'problem' ? 'block' : 'none' }}>
        <div className="space-y-6">
          {/* Key Insight */}
          <div className="bg-rose-50 dark:bg-rose-900/20 border border-rose-200 dark:border-rose-800 rounded-lg p-6">
            <h3 className="text-xl font-semibold text-rose-800 dark:text-rose-200 mb-3">
              The Core Problem: What's Your Denominator?
            </h3>
            <p className="text-rose-700 dark:text-rose-300 mb-4">
              In {selectedYear}, police fatally shot <strong>{benchmarkData[0].years[selectedYear].blackShot} Black citizens</strong> and <strong>{benchmarkData[0].years[selectedYear].whiteShot} White citizens</strong>.
              Black citizens are ~13% of the US population but ~26% of those fatally shot.
              Does this prove racial bias?
            </p>
            <p className="text-rose-700 dark:text-rose-300 font-medium">
              It depends entirely on what you compare these numbers to—your choice of <em>denominator</em> or <em>benchmark</em>.
            </p>
          </div>

          {/* The Iceberg Metaphor */}
          <div className="card p-6">
            <h3 className="text-lg font-semibold mb-4">The "Iceberg Phenomenon"</h3>
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  When analyzing rates, we need both a <strong>numerator</strong> (what happened) and
                  a <strong>denominator</strong> (the at-risk population). The denominator is like the
                  hidden part of an iceberg—often unseen, but critical.
                </p>
                <ul className="space-y-2 text-sm text-gray-600 dark:text-gray-400">
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 dark:text-green-400 font-bold">✓</span>
                    <span><strong>Numerator:</strong> Fatal OIS by race (known from Washington Post data)</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-amber-600 dark:text-amber-400 font-bold">?</span>
                    <span><strong>Denominator:</strong> Who is at risk of being shot? (debated)</span>
                  </li>
                </ul>
              </div>
              <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
                <h4 className="font-medium mb-3">The Formula</h4>
                <div className="bg-white dark:bg-gray-900 rounded p-4 font-mono text-sm text-center">
                  <div className="mb-2">
                    <span className="text-blue-600 dark:text-blue-400">[Black Shot ÷ Black Benchmark]</span>
                  </div>
                  <div className="border-t border-gray-300 dark:border-gray-600 my-2"></div>
                  <div>
                    <span className="text-rose-600 dark:text-rose-400">[White Shot ÷ White Benchmark]</span>
                  </div>
                </div>
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-2 text-center">
                  Odds Ratio: &gt;1 means Black more likely, &lt;1 means White more likely
                </p>
              </div>
            </div>
          </div>

          {/* Why Population Fails */}
          <div className="card p-6 border-l-4 border-amber-500">
            <h3 className="text-lg font-semibold mb-4">Why Population is a Flawed Benchmark</h3>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Using population assumes <em>everyone has an equal chance of encountering police</em>.
              This is demonstrably false:
            </p>
            <ul className="space-y-2 text-gray-600 dark:text-gray-400">
              <li>• Black citizens are more likely to be stopped by police</li>
              <li>• Black citizens are more likely to be arrested</li>
              <li>• Most people (of any race) never have police encounters that could turn lethal</li>
              <li>• The "at-risk" population is not the general population</li>
            </ul>
          </div>

          {/* Quick Comparison */}
          <div className="grid md:grid-cols-2 gap-4">
            <div className="value-box">
              <div className="value-box-title">Using Population ({selectedYear})</div>
              <div className="value-box-value text-rose-600 dark:text-rose-400">
                {allOddsRatios.find(o => o.id === 'population')?.oddsRatio.toFixed(2)}x
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Black citizens more likely to be shot</div>
            </div>
            <div className="value-box">
              <div className="value-box-title">Using Weapons Arrests ({selectedYear})</div>
              <div className="value-box-value text-blue-600 dark:text-blue-400">
                {(1 / (allOddsRatios.find(o => o.id === 'weapons_arrests')?.oddsRatio || 1)).toFixed(2)}x
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">White citizens more likely to be shot</div>
            </div>
          </div>

          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4 text-center">
            <p className="text-lg font-medium text-gray-900 dark:text-gray-100">
              Same numerator. Different denominators. <span className="text-accent-burgundy dark:text-accent-gold">Opposite conclusions.</span>
            </p>
          </div>
        </div>
      </div>

      <div style={{ display: activeTab === 'compare' ? 'block' : 'none' }}>
        <div className="space-y-6">
          {/* Comparison Chart */}
          <div className="card p-6">
            <h3 className="text-lg font-semibold mb-4">Odds Ratios by Benchmark ({selectedYear})</h3>
            <PlotWrapper
              key={`comparison-${selectedYear}`}
              data={[
                {
                  x: allOddsRatios.map((o) => o.oddsRatio),
                  y: allOddsRatios.map((o) => o.name),
                  type: 'bar',
                  orientation: 'h',
                  marker: {
                    color: allOddsRatios.map((o) =>
                      o.oddsRatio > 1 ? '#dc2626' : '#2563eb'
                    ),
                  },
                  text: allOddsRatios.map((o) => o.oddsRatio.toFixed(2)),
                  textposition: 'outside',
                  hovertemplate: '%{y}: %{x:.2f}<extra></extra>',
                },
              ]}
              layout={{
                ...baseLayout,
                autosize: true,
                height: 400,
                margin: { l: 130, r: 60, t: 30, b: 60 },
                showlegend: false,
                xaxis: {
                  title: 'Odds Ratio (Black vs White)',
                  gridcolor: isDark ? '#374151' : '#e5e7eb',
                  zeroline: false,
                  range: [0, 4.5],
                  dtick: 1,
                },
                yaxis: {
                  ...baseLayout.yaxis,
                  automargin: true,
                },
                shapes: [
                  {
                    type: 'line',
                    xref: 'x',
                    yref: 'paper',
                    x0: 1,
                    x1: 1,
                    y0: 0,
                    y1: 1,
                    line: { color: isDark ? '#fbbf24' : '#b45309', width: 2, dash: 'dot' },
                  },
                ],
                annotations: [
                  {
                    x: 1,
                    xref: 'x',
                    y: 1.08,
                    yref: 'paper',
                    text: 'No disparity (1.0)',
                    showarrow: false,
                    font: { size: 11, color: isDark ? '#fbbf24' : '#b45309' },
                  },
                ],
              }}
              config={{ responsive: true, displayModeBar: false }}
              style={{ width: '100%', height: '400px' }}
            />
            <div className="flex justify-center gap-8 mt-4 text-sm">
              <div className="flex items-center gap-2">
                <div className="w-4 h-4 bg-rose-600 rounded"></div>
                <span className="text-gray-600 dark:text-gray-400">Black more likely (&gt;1)</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="w-4 h-4 bg-blue-600 rounded"></div>
                <span className="text-gray-600 dark:text-gray-400">White more likely (&lt;1)</span>
              </div>
            </div>
          </div>

          {/* Data Table */}
          <div className="card p-6">
            <h3 className="text-lg font-semibold mb-4">Detailed Comparison ({selectedYear})</h3>
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-200 dark:border-gray-700">
                    <th className="px-4 py-2 text-left font-medium text-gray-500 dark:text-gray-400">Benchmark</th>
                    <th className="px-4 py-2 text-right font-medium text-gray-500 dark:text-gray-400">Black Benchmark</th>
                    <th className="px-4 py-2 text-right font-medium text-gray-500 dark:text-gray-400">White Benchmark</th>
                    <th className="px-4 py-2 text-center font-medium text-gray-500 dark:text-gray-400">Odds Ratio</th>
                    <th className="px-4 py-2 text-left font-medium text-gray-500 dark:text-gray-400">Interpretation</th>
                  </tr>
                </thead>
                <tbody>
                  {benchmarkData.map((b) => {
                    const yearData = b.years[selectedYear];
                    const or = calculateOddsRatio(yearData.blackShot, yearData.whiteShot, yearData.black, yearData.white);
                    return (
                      <tr key={b.id} className="border-b border-gray-200 dark:border-gray-700">
                        <td className="px-4 py-3 font-medium text-gray-900 dark:text-gray-100">{b.name}</td>
                        <td className="px-4 py-3 text-right text-gray-600 dark:text-gray-400">{yearData.black.toLocaleString()}</td>
                        <td className="px-4 py-3 text-right text-gray-600 dark:text-gray-400">{yearData.white.toLocaleString()}</td>
                        <td className={`px-4 py-3 text-center font-bold ${or > 1 ? 'text-rose-600 dark:text-rose-400' : 'text-blue-600 dark:text-blue-400'}`}>
                          {or.toFixed(2)}
                        </td>
                        <td className="px-4 py-3 text-gray-600 dark:text-gray-400">
                          {or > 1 ? `Black ${or.toFixed(1)}x more likely` : `White ${(1/or).toFixed(1)}x more likely`}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-4">
              Note: Fatal OIS in {selectedYear}: {benchmarkData[0].years[selectedYear].blackShot} Black, {benchmarkData[0].years[selectedYear].whiteShot} White
            </p>
          </div>

          {/* Benchmark Categories */}
          <div className="grid md:grid-cols-3 gap-4">
            <div className="card p-4 border-t-4 border-purple-500">
              <h4 className="font-semibold text-purple-700 dark:text-purple-300 mb-2">Population-Based</h4>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                Census data. Simple but flawed—assumes equal police contact rates.
              </p>
              <div className="mt-2 text-lg font-bold text-purple-600 dark:text-purple-400">
                OR: {allOddsRatios.find(o => o.id === 'population')?.oddsRatio.toFixed(2)}
              </div>
            </div>
            <div className="card p-4 border-t-4 border-amber-500">
              <h4 className="font-semibold text-amber-700 dark:text-amber-300 mb-2">Interaction-Based</h4>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                PPCS survey data. Better than population but most contacts are low-risk.
              </p>
              <div className="mt-2 text-lg font-bold text-amber-600 dark:text-amber-400">
                OR: {allOddsRatios.find(o => o.id === 'street_stops')?.oddsRatio.toFixed(2)}
              </div>
            </div>
            <div className="card p-4 border-t-4 border-teal-500">
              <h4 className="font-semibold text-teal-700 dark:text-teal-300 mb-2">Arrest-Based</h4>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                UCR arrest data. Closer to lethal-risk situations but may reflect enforcement bias.
              </p>
              <div className="mt-2 text-lg font-bold text-teal-600 dark:text-teal-400">
                OR: {allOddsRatios.find(o => o.id === 'weapons_arrests')?.oddsRatio.toFixed(2)}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div style={{ display: activeTab === 'explore' ? 'block' : 'none' }}>
        <div className="space-y-6">
          {/* Benchmark Selector */}
          <div className="card p-6">
            <h3 className="text-lg font-semibold mb-4">Select a Benchmark to Explore</h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
              {benchmarkData.map((b) => (
                <button
                  key={b.id}
                  onClick={() => setSelectedBenchmark(b.id)}
                  className={`p-3 rounded-lg text-sm font-medium transition-colors text-left ${
                    selectedBenchmark === b.id
                      ? 'bg-primary-700 text-white'
                      : 'bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700'
                  }`}
                >
                  {b.shortName}
                </button>
              ))}
            </div>
          </div>

          {/* Selected Benchmark Details */}
          <div className="grid lg:grid-cols-2 gap-6">
            <div className="card p-6">
              <h3 className="text-lg font-semibold mb-2">{currentBenchmark.name}</h3>
              <p className="text-gray-600 dark:text-gray-400 mb-4">{currentBenchmark.description}</p>

              <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-700 rounded-lg p-4 mb-4">
                <h4 className="font-medium text-amber-800 dark:text-amber-200 mb-1">Limitation</h4>
                <p className="text-sm text-amber-700 dark:text-amber-300">{currentBenchmark.limitation}</p>
              </div>

              <div className="space-y-3">
                <div className="flex justify-between py-2 border-b border-gray-200 dark:border-gray-700">
                  <span className="text-gray-600 dark:text-gray-400">Black Benchmark ({selectedYear})</span>
                  <span className="font-medium">{currentYearData.black.toLocaleString()}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-200 dark:border-gray-700">
                  <span className="text-gray-600 dark:text-gray-400">White Benchmark ({selectedYear})</span>
                  <span className="font-medium">{currentYearData.white.toLocaleString()}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-200 dark:border-gray-700">
                  <span className="text-gray-600 dark:text-gray-400">Black Fatally Shot</span>
                  <span className="font-medium">{currentYearData.blackShot}</span>
                </div>
                <div className="flex justify-between py-2">
                  <span className="text-gray-600 dark:text-gray-400">White Fatally Shot</span>
                  <span className="font-medium">{currentYearData.whiteShot}</span>
                </div>
              </div>
            </div>

            <div className="card p-6">
              <h3 className="text-lg font-semibold mb-4">Result</h3>

              <div className={`p-6 rounded-lg text-center mb-4 ${
                currentOddsRatio > 1
                  ? 'bg-rose-50 dark:bg-rose-900/20'
                  : 'bg-blue-50 dark:bg-blue-900/20'
              }`}>
                <div className="text-sm text-gray-600 dark:text-gray-400 mb-1">Odds Ratio</div>
                <div className={`text-5xl font-bold ${
                  currentOddsRatio > 1
                    ? 'text-rose-600 dark:text-rose-400'
                    : 'text-blue-600 dark:text-blue-400'
                }`}>
                  {currentOddsRatio.toFixed(2)}
                </div>
                <div className={`text-lg mt-2 ${
                  currentOddsRatio > 1
                    ? 'text-rose-700 dark:text-rose-300'
                    : 'text-blue-700 dark:text-blue-300'
                }`}>
                  {currentOddsRatio > 1
                    ? `Black citizens ${currentOddsRatio.toFixed(1)}x more likely to be fatally shot`
                    : `White citizens ${(1/currentOddsRatio).toFixed(1)}x more likely to be fatally shot`
                  }
                </div>
              </div>

              <div className="text-sm text-gray-600 dark:text-gray-400">
                <h4 className="font-medium mb-2">Calculation:</h4>
                <div className="bg-gray-50 dark:bg-gray-800 rounded p-3 font-mono text-xs">
                  <div>Black rate: {currentYearData.blackShot} / {currentYearData.black.toLocaleString()} = {(currentYearData.blackShot / currentYearData.black * 100000).toFixed(2)} per 100k</div>
                  <div>White rate: {currentYearData.whiteShot} / {currentYearData.white.toLocaleString()} = {(currentYearData.whiteShot / currentYearData.white * 100000).toFixed(2)} per 100k</div>
                  <div className="mt-2 pt-2 border-t border-gray-300 dark:border-gray-600">
                    OR = {(currentYearData.blackShot / currentYearData.black * 100000).toFixed(2)} / {(currentYearData.whiteShot / currentYearData.white * 100000).toFixed(2)} = <strong>{currentOddsRatio.toFixed(2)}</strong>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Visual Comparison */}
          <div className="card p-6">
            <h3 className="text-lg font-semibold mb-4">Rate Comparison ({currentBenchmark.shortName})</h3>
            <PlotWrapper
              key={`rate-${selectedYear}-${selectedBenchmark}`}
              data={[
                {
                  x: ['Black Citizens', 'White Citizens'],
                  y: [
                    currentYearData.blackShot / currentYearData.black * 100000,
                    currentYearData.whiteShot / currentYearData.white * 100000,
                  ],
                  type: 'bar',
                  marker: {
                    color: ['#3b82f6', '#9ca3af'],
                  },
                  text: [
                    (currentYearData.blackShot / currentYearData.black * 100000).toFixed(2),
                    (currentYearData.whiteShot / currentYearData.white * 100000).toFixed(2),
                  ],
                  textposition: 'outside',
                },
              ]}
              layout={{
                ...baseLayout,
                autosize: true,
                height: 300,
                margin: { l: 60, r: 20, t: 20, b: 60 },
                showlegend: false,
                yaxis: {
                  ...baseLayout.yaxis,
                  title: 'Fatal OIS per 100,000',
                },
              }}
              config={{ responsive: true, displayModeBar: false }}
              style={{ width: '100%', height: '300px' }}
            />
          </div>
        </div>
      </div>

      <div style={{ display: activeTab === 'custom' ? 'block' : 'none' }}>
        <div className="space-y-6">
          <div className="bg-purple-50 dark:bg-purple-900/20 border border-purple-200 dark:border-purple-800 rounded-lg p-4">
            <h4 className="font-semibold text-purple-800 dark:text-purple-200 mb-2">Build Your Own Scenario</h4>
            <p className="text-purple-700 dark:text-purple-300 text-sm">
              Enter custom values to see how different numerators and denominators affect the odds ratio.
              This helps illustrate why benchmark selection is so critical.
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-6">
            {/* Inputs */}
            <div className="card p-6">
              <h3 className="text-lg font-semibold mb-4">Input Values</h3>

              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm text-gray-600 dark:text-gray-400 mb-1">Black Fatally Shot</label>
                    <input
                      type="number"
                      value={customBlackShot}
                      onChange={(e) => setCustomBlackShot(Math.max(0, parseInt(e.target.value) || 0))}
                      className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                    />
                  </div>
                  <div>
                    <label className="block text-sm text-gray-600 dark:text-gray-400 mb-1">White Fatally Shot</label>
                    <input
                      type="number"
                      value={customWhiteShot}
                      onChange={(e) => setCustomWhiteShot(Math.max(0, parseInt(e.target.value) || 0))}
                      className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm text-gray-600 dark:text-gray-400 mb-1">Black Benchmark</label>
                    <input
                      type="number"
                      value={customBlackBenchmark}
                      onChange={(e) => setCustomBlackBenchmark(Math.max(1, parseInt(e.target.value) || 1))}
                      className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                    />
                  </div>
                  <div>
                    <label className="block text-sm text-gray-600 dark:text-gray-400 mb-1">White Benchmark</label>
                    <input
                      type="number"
                      value={customWhiteBenchmark}
                      onChange={(e) => setCustomWhiteBenchmark(Math.max(1, parseInt(e.target.value) || 1))}
                      className="w-full px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
                    />
                  </div>
                </div>

                <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
                  <h4 className="font-medium mb-2">Quick Presets</h4>
                  <div className="flex flex-wrap gap-2">
                    {benchmarkData.map((b) => (
                      <button
                        key={b.id}
                        onClick={() => {
                          const data = b.years[selectedYear];
                          setCustomBlackShot(data.blackShot);
                          setCustomWhiteShot(data.whiteShot);
                          setCustomBlackBenchmark(data.black);
                          setCustomWhiteBenchmark(data.white);
                        }}
                        className="px-3 py-1 text-xs bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-full transition-colors"
                      >
                        {b.shortName}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Result */}
            <div className="card p-6">
              <h3 className="text-lg font-semibold mb-4">Your Result</h3>

              <div className={`p-6 rounded-lg text-center mb-4 ${
                customOddsRatio > 1
                  ? 'bg-rose-50 dark:bg-rose-900/20'
                  : 'bg-blue-50 dark:bg-blue-900/20'
              }`}>
                <div className="text-sm text-gray-600 dark:text-gray-400 mb-1">Odds Ratio</div>
                <div className={`text-5xl font-bold ${
                  customOddsRatio > 1
                    ? 'text-rose-600 dark:text-rose-400'
                    : 'text-blue-600 dark:text-blue-400'
                }`}>
                  {isFinite(customOddsRatio) ? customOddsRatio.toFixed(2) : '—'}
                </div>
                <div className={`text-lg mt-2 ${
                  customOddsRatio > 1
                    ? 'text-rose-700 dark:text-rose-300'
                    : 'text-blue-700 dark:text-blue-300'
                }`}>
                  {isFinite(customOddsRatio) && (
                    customOddsRatio > 1
                      ? `Black ${customOddsRatio.toFixed(1)}x more likely`
                      : `White ${(1/customOddsRatio).toFixed(1)}x more likely`
                  )}
                </div>
              </div>

              <div className="text-sm text-gray-600 dark:text-gray-400">
                <div className="bg-gray-50 dark:bg-gray-800 rounded p-3 font-mono text-xs">
                  <div>Black rate: {customBlackShot} / {customBlackBenchmark.toLocaleString()} = {(customBlackShot / customBlackBenchmark * 100000).toFixed(4)} per 100k</div>
                  <div>White rate: {customWhiteShot} / {customWhiteBenchmark.toLocaleString()} = {(customWhiteShot / customWhiteBenchmark * 100000).toFixed(4)} per 100k</div>
                  <div className="mt-2 pt-2 border-t border-gray-300 dark:border-gray-600">
                    Odds Ratio = <strong>{isFinite(customOddsRatio) ? customOddsRatio.toFixed(2) : '—'}</strong>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Key Takeaway */}
          <div className="card p-6 bg-gray-50 dark:bg-gray-800">
            <h3 className="text-lg font-semibold mb-4">Key Takeaways</h3>
            <ul className="space-y-3 text-gray-600 dark:text-gray-400">
              <li className="flex items-start gap-3">
                <span className="text-primary-700 dark:text-primary-400 font-bold">1.</span>
                <span><strong>Disparity ≠ Bias:</strong> Observed disparities depend heavily on benchmark choice. Different benchmarks yield different—even opposite—conclusions.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-primary-700 dark:text-primary-400 font-bold">2.</span>
                <span><strong>No perfect benchmark exists:</strong> Each has strengths and limitations. Population is convenient but flawed. Arrests may reflect enforcement bias.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-primary-700 dark:text-primary-400 font-bold">3.</span>
                <span><strong>Context matters:</strong> The "at-risk" population for fatal OIS is not the general population—it's those who encounter police in potentially lethal situations.</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-primary-700 dark:text-primary-400 font-bold">4.</span>
                <span><strong>Be skeptical of simple claims:</strong> Anyone citing disparity statistics without discussing their benchmark choice is presenting incomplete analysis.</span>
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* Footer Citation */}
      <div className="mt-8 p-4 bg-gray-50 dark:bg-gray-800 rounded-lg">
        <p className="text-sm text-gray-600 dark:text-gray-400">
          <strong>Reference:</strong> Tregle, B., Nix, J., & Alpert, G. P. (2018). Disparity does not mean bias:
          Making sense of observed racial disparities in fatal officer-involved shootings with multiple benchmarks.
          <em> Journal of Crime and Justice</em>.{' '}
          <a
            href="https://doi.org/10.1080/0735648X.2018.1547269"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent-burgundy dark:text-accent-gold hover:underline"
          >
            https://doi.org/10.1080/0735648X.2018.1547269
          </a>
        </p>
      </div>
    </div>
  );
}
